const PERMISSIONS = {
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_LIST_FILTER: "USER_LIST_FILTER",
  USER_LIST: "USER_LIST",
};

module.exports = { PERMISSIONS };
